package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cheewaio/gogql-starter/graph/model"
	"github.com/cheewaio/gogql-starter/graph/response"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input model.NewNote) (*model.NoteResponse, error) {
	user := r.GetCurrentUser(ctx)
	if user == nil {
		return response.Failure(ctx, &model.NoteResponse{}, fmt.Errorf("authentication required"))
	}
	note, err := r.NoteService.Create(ctx, user.Username, user.Username, input.Title, input.Content)
	if err != nil {
		return response.Failure(ctx, &model.NoteResponse{}, err)
	}
	return response.Success(ctx, &model.NoteResponse{Note: note})
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, input model.UpdateNoteInput) (*model.NoteResponse, error) {
	user := r.GetCurrentUser(ctx)
	if user == nil {
		return response.Failure(ctx, &model.NoteResponse{}, fmt.Errorf("authentication required"))
	}
	note, err := r.NoteService.Update(ctx, user.Username, id, input.Title, input.Content)
	if err != nil {
		return response.Failure(ctx, &model.NoteResponse{}, err)
	}
	return response.Success(ctx, &model.NoteResponse{Note: note})
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (*model.DeleteResponse, error) {
	user := r.GetCurrentUser(ctx)
	if user == nil {
		return response.Failure(ctx, &model.DeleteResponse{}, fmt.Errorf("authentication required"))
	}
	if err := r.NoteService.Delete(ctx, user.Username, id); err != nil {
		return response.Failure(ctx, &model.DeleteResponse{}, err)
	}
	return response.Success(ctx, &model.DeleteResponse{})
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := r.GetCurrentUser(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	id := uuid.NewSHA1(uuid.NameSpaceDNS, []byte(user.Username)).String()
	return &model.User{ID: id, Username: user.Username}, nil
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*model.Note, error) {
	user := r.GetCurrentUser(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	return r.NoteService.GetByID(ctx, user.Username, id)
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context, input *model.PageInput, filter *model.FilterInput) (*model.NoteConnection, error) {
	user := r.GetCurrentUser(ctx)
	if user == nil {
		return nil, fmt.Errorf("authentication required")
	}
	q, err := parseQueryInput(input, filter)
	if err != nil {
		return nil, err
	}
	return r.NoteService.List(ctx, user.Username, q)
}
