// Package graph provides the GraphQL resolver layer. It bridges the schema
// definitions (generated by gqlgen) with the service layer, handling
// authentication extraction, input parsing, and response formatting.
package graph

import (
	"context"

	"github.com/cheewaio/gogql-starter/internal/auth"
	"github.com/cheewaio/gogql-starter/internal/service"
)

// Resolver serves as the dependency container for all GraphQL resolvers.
// It is injected by gqlgen into every resolver method via the generated code.
type Resolver struct {
	NoteService *service.NoteService
}

// NewResolver creates a new Resolver with the given services injected.
func NewResolver(noteService *service.NoteService) *Resolver {
	return &Resolver{NoteService: noteService}
}

// GetCurrentUser extracts the authenticated user from the request context.
// Returns nil if the request is unauthenticated.
func (r *Resolver) GetCurrentUser(ctx context.Context) *auth.User {
	user, _ := auth.UserFromContext(ctx)
	return user
}
