// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type MutationResponse interface {
	IsMutationResponse()
	GetCode() int32
	GetSuccess() bool
	GetMessage() *string
}

type DeleteResponse struct {
	Code    int32   `json:"code"`
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

func (DeleteResponse) IsMutationResponse()      {}
func (this DeleteResponse) GetCode() int32      { return this.Code }
func (this DeleteResponse) GetSuccess() bool    { return this.Success }
func (this DeleteResponse) GetMessage() *string { return this.Message }

type FilterCriteria struct {
	Field    string         `json:"field"`
	Operator FilterOperator `json:"operator"`
	Value    *string        `json:"value,omitempty"`
}

type FilterInput struct {
	Filters []*FilterCriteria `json:"filters,omitempty"`
	Logic   FilterLogic       `json:"logic"`
}

type Mutation struct {
}

type NewNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Note struct {
	ID         string    `json:"id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"createdAt"`
	ModifiedAt time.Time `json:"modifiedAt"`
	User       *User     `json:"user"`
}

type NoteConnection struct {
	Items    []*Note   `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type NoteResponse struct {
	Code    int32   `json:"code"`
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	Note    *Note   `json:"note,omitempty"`
}

func (NoteResponse) IsMutationResponse()      {}
func (this NoteResponse) GetCode() int32      { return this.Code }
func (this NoteResponse) GetSuccess() bool    { return this.Success }
func (this NoteResponse) GetMessage() *string { return this.Message }

type PageInfo struct {
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
}

type PageInput struct {
	First  *int32       `json:"first,omitempty"`
	After  *string      `json:"after,omitempty"`
	Last   *int32       `json:"last,omitempty"`
	Before *string      `json:"before,omitempty"`
	Sort   []*SortField `json:"sort,omitempty"`
}

type Query struct {
}

type SortField struct {
	Field string `json:"field"`
	Asc   bool   `json:"asc"`
}

type UpdateNoteInput struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

type FilterLogic string

const (
	FilterLogicAnd FilterLogic = "AND"
	FilterLogicOr  FilterLogic = "OR"
)

var AllFilterLogic = []FilterLogic{
	FilterLogicAnd,
	FilterLogicOr,
}

func (e FilterLogic) IsValid() bool {
	switch e {
	case FilterLogicAnd, FilterLogicOr:
		return true
	}
	return false
}

func (e FilterLogic) String() string {
	return string(e)
}

func (e *FilterLogic) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterLogic(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterLogic", str)
	}
	return nil
}

func (e FilterLogic) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FilterLogic) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FilterLogic) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FilterOperator string

const (
	FilterOperatorEq        FilterOperator = "EQ"
	FilterOperatorNeq       FilterOperator = "NEQ"
	FilterOperatorContains  FilterOperator = "CONTAINS"
	FilterOperatorGt        FilterOperator = "GT"
	FilterOperatorGte       FilterOperator = "GTE"
	FilterOperatorLt        FilterOperator = "LT"
	FilterOperatorLte       FilterOperator = "LTE"
	FilterOperatorIsNull    FilterOperator = "IS_NULL"
	FilterOperatorIsNotNull FilterOperator = "IS_NOT_NULL"
)

var AllFilterOperator = []FilterOperator{
	FilterOperatorEq,
	FilterOperatorNeq,
	FilterOperatorContains,
	FilterOperatorGt,
	FilterOperatorGte,
	FilterOperatorLt,
	FilterOperatorLte,
	FilterOperatorIsNull,
	FilterOperatorIsNotNull,
}

func (e FilterOperator) IsValid() bool {
	switch e {
	case FilterOperatorEq, FilterOperatorNeq, FilterOperatorContains, FilterOperatorGt, FilterOperatorGte, FilterOperatorLt, FilterOperatorLte, FilterOperatorIsNull, FilterOperatorIsNotNull:
		return true
	}
	return false
}

func (e FilterOperator) String() string {
	return string(e)
}

func (e *FilterOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilterOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilterOperator", str)
	}
	return nil
}

func (e FilterOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FilterOperator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FilterOperator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
