// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID         uuid.UUID
	Content    string
	CreatedAt  time.Time
	ModifiedAt time.Time
	UserID     uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Username string
}
